double DEFAULT_TEXT_SIZE = 20;
double STRONG_TEXT_SIZE = 27;
double SUB_TEXT_SIZE = 16;
double DEFAULT_AVATAR_SIZE = 40;
double DEFAULT_THUMBNAIL_SIZE = 70;
double BIG_TEXT_SIZE = 60;
double ROOM_THUMBNAIL_SIZE = 60;